# Generated by Django 5.1.2 on 2024-11-07 07:55

import datetime
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', multiselectfield.db.fields.MultiSelectField(choices=[(0, '웹사이트'), (1, '앱개발'), (2, 'BI/BX'), (3, '마케팅'), (4, '유지보수'), (5, '영상제작'), (6, '카탈로그'), (7, '컨설팅'), (8, '인터뷰요청'), (9, '기타문의')], max_length=10, verbose_name='필요서비스')),
                ('company_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='회사명')),
                ('manager_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='담당자명')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='연락처')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일')),
                ('request', multiselectfield.db.fields.MultiSelectField(choices=[(0, '신규구축'), (1, '개선구축'), (2, '컨설팅'), (3, '유지보수'), (4, '기타')], max_length=5, verbose_name='의뢰요청')),
                ('started', models.DateField(default=datetime.date(2024, 1, 1), verbose_name='예상시작일')),
                ('ended', models.DateField(default=datetime.date(2030, 12, 31), verbose_name='예상종료일')),
                ('budget', models.CharField(max_length=10, verbose_name='예산')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '의뢰목록',
                'verbose_name_plural': '의뢰목록',
            },
        ),
    ]
